mobile_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


admin.site. site_header ='Mobile Pouch Adn Page'
admin. site. index_title = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),  
    path('account/',include('registration.urls')),
    path('orders/', include('orders.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
        path('', views.homei,name='home'),
        path('filter_brand/<int:id>/',views.filter_brand,name='filter_brand'),
        path('filter_phone/<int:id>/',views.products_page,name='products_page'),
        path('view_all/',views.view_all,name='view_all'),


        path('category/<slug:brand_slug>/<slug:phone_name_slug>/<slug:product_slug>/', views.product_details,name='product_details'),
        path('cart/', views.cart ,name='cart'),
        path('addcart/<int:product_id>/', views.addcart,name='addcart'),
        path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart,name='remove_cart'),
        path('remove_items/<int:product_id>/<int:cart_item_id>/', views.remove_items,name='remove_items'),


        path('checkout/', views.checkout,name='checkout'),


        path('search/', views.search_products, name='search_products'),


        
        
] + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.urls import reverse
from registration.models import Account
from django.db.models import Avg,Count
from django.core.files.images import ImageFile
from PIL import Image
# Create your models here.




class Category(models.Model):
    category_name    = models.CharField(max_length=50,unique=True)
    slug             = models.SlugField(max_length=50,unique=True)
    description      = models.CharField(max_length=300,blank=True)
    category_image   = models.ImageField(upload_to = 'photos/category')
   

    class Meta:
        verbose_name        = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('products_by_category',args=[self.slug])    


    def __str__(self):
        return self.category_name
    

    def save(self):
        if self.category_image:          
            super(Category, self).save()
            category_image = Image.open(self.category_image)
            (width , height) = category_image.size     
            size = (720,480)
            image = category_image.resize(size, Image.ANTIALIAS)
            image.save(self.category_image.path)
        # else:
        #     if self.rent_property_category:  
        #         super(SellProperty, self).save()




class Sub_Category(models.Model):
    sub_categoryname = models.CharField(max_length=50,unique=True)
    slug        = models.SlugField(max_length=50,unique=True)
    description      = models.CharField(max_length=300,blank=True)
    category        = models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category_image       = models.ImageField(upload_to = 'photos/sub_category')


    def get_url(self):
        return reverse('products_by_subcategory',args=[self.category.slug, self.slug])  

    def __str__(self):
        return self.sub_categoryname





class Product(models.Model):
    product_name    = models.CharField(max_length=100,unique=True)
    slug            = models.SlugField(max_length=100,unique=True)
    description     = models.TextField(max_length=300,blank = True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to = 'photos/product')
    images1          = models.ImageField(upload_to = 'photos/product',blank=True,null=True)
    images2          = models.ImageField(upload_to = 'photos/product',blank=True,null=True)
    images3          = models.ImageField(upload_to = 'photos/product',blank=True,null=True)
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    brand        = models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    phone_name    = models.ForeignKey(Sub_Category,on_delete=models.CASCADE)  


    def get_url(self):
        return reverse('product_details',args=[self.brand.slug,self.phone_name.slug,self.slug])
     
    def __str__(self) :
        return self.product_name 



    def averageReview(self):
        reviews  = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviews['average'] is not None:
            avg= float(reviews['average'])
        return avg        

    def countReview(self):
        reviews  = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count= int(reviews['count'])
        return count  

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category = 'color', is_active=True )

    def sizes(self):
        return super(VariationManager,self).filter(variation_category = 'size', is_active=True )

variation_category_choice =  (
    ('color','color'),
    ('size','size'),
)


class Variation(models.Model):
    product     = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category  =   models.CharField(max_length=100,choices= variation_category_choice,)
    variation_value = models.CharField(max_length=100,null=True)
    is_active   = models.BooleanField(default=True )
    created_date    = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

       




class Cart(models.Model):
    cart_id = models.CharField(max_length=100,)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class Cartitems(models.Model):
    user = models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation,blank=True)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.product

    def sub_total(self):
        return self.product.price * self.quantity



class ReviewRating(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    subjects = models.CharField(max_length=50,blank = True)
    review = models.TextField(max_length=500,blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20,blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
        
    def __str__(self):
             return self.subjects

templates/store_template/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}about

{%block main-content %}
<div id="searchResults"></div>
<div class="container">
    <div id="srchrlt" class="d-flex flex-wrap"></div>
  </div>
  
      <div class="container ">
        
          <div class="row">
            {% for cart_item in cart_items %}

              <div class="col-md-6 view-cart " >
                  <div class="cartpage">
                      <div class="cartpageimg">
                  
                            <div class="parent" style="position:relative;">
                         
                                <a href="{{ cart_item.product.get_url }}">
                                <img src="{{ cart_item.product.images.url }}" alt="Product">
                            </a>
                            </div>
                       
  
                          
                      </div>
                    
      
     
                      <div class="cartpagecontent text-start  px-3">
               
                          <h5 class="mt-2" style="font-weight: bold; font-size: 18px; margin-bottom: 0.5rem;">
                            {{cart_item.product.product_name}}</h5>
                            <h5>Price: {{cart_item.product.price}}</h5>
                            <h5>Quantity: {{cart_item.quantity}}</h5>
                            
                 
                          <div class="update-cart d-flex">
                            <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}">  <button  class="btn btn-link px-2"  type="submit"
                                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                <i class="fas fa-minus"></i></button></a>
                                <input type="text" name="quantity" value="{{cart_item.quantity}}" type="number"
                                  style="width:2rem ;" class="form-control form-control-sm"  min="1"/>

                                  <form action="{% url 'addcart' cart_item.product.id %}" method="POST">
                                    {% csrf_token %}
                                    {% for item in cart_item.variations.all %}
                                    <input type="hidden" name="{{ item.variation_category | lower }}"
                                      value="{{ item.variation_value | capfirst }}">
          
                                    {% endfor %}
                                    <button class="btn btn-link px-2" type="submit"
                                      onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                      <i class="fas fa-plus"></i>
                                  </form>
                       
                            {% comment %} <input style="height:max-content;" class="form-control input-sm w-auto"   name="qty" type="number" value="10"  min="1">   {% endcomment %}
                            {% comment %} <input type="submit"  style="background-color: #f5831a;color:#fff;" class="btn rd-stroke-btn border_1px dart-btn-xs mx-2 w-auto" value="Update Cart"> {% endcomment %}
                         
                    
                    </div>

                          <h5>Total Price:{{ cart_item.sub_total }}</h5>
                          <a href="{% url 'remove_items' cart_item.product.id cart_item.id %}" t class=" bg-dark border-0  btn btn-primary removecart">Remove</a>
                      </div>
                  </div>
  
              </div>
                 
                      {% endfor %}

            
              <div class="col-md-6  view-cart">
                  <div class="table-responsive">
                      <table class="px-5 cartpagetable table">
                          <tbody>
                              <tr>
                                  <td class=" text-start py-2">Sub-total</td>
                                  <td class=" text-end py-2">{{total}}</td>
                              </tr>
                              {% comment %} <tr>
                                  <td class=" text-start py-2">Tax</td>
                                  <td class=" text-end py-2">{{tax}}</td>
                              </tr> {% endcomment %}
                              <tr>
                                <td class=" text-start py-2">Grand Total</td>
                                <td class=" text-end py-2">{{grand_total}}</td>
                            </tr>
                              <tr>
                                  
                              </tr>
                          </tbody>
                          
                      </table>
                      <div class="py-4">
                          <a href="Payment.html">
                              <a href="{% url 'checkout' %}"
                                  style="background: rgb(245, 131, 26);"
                                  class="border-0 btn btn-primary proceed-to-buy">Proceed To Buy</a> 
                              </a>
                        </div>
                  </div>
              </div>
          </div>
      </div>
  
   


{%endblock main-content%} 

templates/store_template/category.html
 {% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}

{%block main-content %}


<div id="searchResults"></div>

{% if filter_brand %}

<section>
    <div class="mb-5 footerclass container">
        <h3 class="text-center">phones</h3>
            <div class="category-main  ">
                <div class="categoriesfooter flex-wrap justify-content-center;">
                    {% for product in filter_brand %}
                    <a href="{% url 'products_page' product.id %}">  
                        <div class="dd ">
                            <img src="{{product.sub_category_image.url}}" alt="itcity">
                            <p class="fw-bold">{{product.sub_categoryname}}</p></div>
                       
                    </a>
                    {% endfor %}
            
                </div>
            </div>
    </div>
 </section>

 {% endif %}





 {% if mobile_phones %}

 <section>
     <div class="mb-5 footerclass container">
         <h3 class="text-center">products</h3>
             <div class="category-main  ">
                 <div class="categoriesfooter flex-wrap justify-content-center;">

                    {% for product in mobile_phones %}
                     <a href="{{ product.get_url }}">  
                         <div class="dd ">
                             <img src="{{product.images.url}}" alt="itcity">
                             <p class="fw-bold">{{product.product_name}}</p></div>
                     </a>
                     {% endfor %}
                 
                 </div>
             </div>
     </div>
  </section>

 
  {% endif %}



  {% if veiw_all_category %}
  <section>
      <div class="mb-5 footerclass container">
          <h3 class="text-center">models</h3>
              <div class="category-main  ">
                  <div class="categoriesfooter flex-wrap justify-content-center;">
 
                     {% for product in veiw_all_category %}
                      <a href="{% url 'filter_brand' product.id %}">  
                          <div class="dd ">
                              <img src="{{product.category_image.url}}" alt="itcity">
                              <p class="fw-bold">{{product.category_name}}</p></div>
                      </a>
                      {% endfor %}
                  
                  </div>
              </div>
      </div>
   </section>
 
  
   {% endif %}


{%endblock main-content%} 

templates/store_template/search_results.html
{% for product in products %}
 


<div class='newdesign'>
    <a href="{{ product.get_url }}"> 
      <img src="{{product.images.url}}" alt="">

    <p style="font-size:14px;margin-bottom:0.5rem;">{{product.phone_name}}</p>
    <p style="font-weight:600;font-size:18px;color: #f5831a;margin-bottom: 4px;" class="">{{product.phone_name}}</p>
    <p style="font-weight:600;font-size:18px;color: #f5831a;margin-bottom: 4px;" class="">{{product.brand}}</p>
    <div class="font-body"><span
        style="font-weight:600;font-size:14px;color: #000;margin-bottom: 4px;text-decoration: line-through;"
        class=" ">{{product.price}}</span> <span class=""
        style="background-color: #f5831a;font-size: 12px;color: white;padding: 3px;">{{product.price}}</span></div>
</a>
      
  </div>

{% endfor %}

templates/store_template/shop-details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}about


{%block main-content %}
{% block css %}
<style>
    #id_quantity {
        padding: 10px;
    }

    .forms {
        border: 0.3px solid gray;
        padding: 10px;
    }
    .btns
    {
        padding:10px;
        border-radius: 5px;
        color: white;
    }
</style>
{% endblock %}



<div class="container">

  <div id="searchResults"></div>
    
    {% if single_product %}
    <div id="srchrlt" class="d-flex flex-wrap"></div>
    </div>
    
        <section class="view-cart">
            <div class="container my-5">
            <div class="row">
                <div class="col-md-6">
                    <div class="product-detail">
                        
    <div class="exzoom" id="exzoom">
      <!-- Images -->
      <div class="exzoom_img_box">
        <ul class='exzoom_img_ul'>
           
          <li>
              <img  src="{{single_product.images.url}}"/>
         </li>
         {% if single_product.image1 %}
         <li>
          <img  src="{{single_product.image1.url}}"/>
     </li>
     {% endif %}

     {% if single_product.image2 %}
     <li>
      <img  src="{{single_product.image2.url}}"/>
 </li>
 {% endif %}
 {% if single_product.image3 %}
 <li>
  <img  src="{{single_product.image3.url}}"/>
</li>
{% endif %}


         
         
        </ul>
      </div>
    
      <div class="exzoom_nav"></div>
    
      <p class="exzoom_btn">
          <a href="javascript:void(0);" class="exzoom_prev_btn"> </a>
          <a href="javascript:void(0);" class="exzoom_next_btn"> </a>
      </p>
    </div>
    </div>
                </div>
                <div class="col-md-6 py-5">
    
                    <div class="row">
                        <div class="col-md-12">
                            <div class="detail-sub-head d-flex">
                                <!-- <h6>APPLE</h6> -->
                                <span class="instock">instock</span>
                            </div>
                            <div class="details-head">
                                <h1>{{single_product.phone_name}}</h1>
                            </div>
                            <div class="details-sub-price">
                                <p>{{ single_product.price }}</p>
                                <h3> {{ single_product.price }}</h3>
                                <span class="discount-percent">{{ single_product.price }}</span>
                            </div>
                            
    </br>
                            <div class="detailcart">
                                <form action="{% url 'addcart' single_product.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="primary-btn">Add to Cart</button>
                                </form>
                            </div>
                   

                           
                            
                            
                            <hr>
                            <div class="details-para">
                                <h6>Product Details</h6>
                                <ul>
                                    <li>description </li>

                                    {{single_product.description}}
                                    
                                </ul>
                              
                            </div>
    
    
    
                        </div>
                    </div>
    
                </div>
            </div>
            {% endif %}
            <div class="container">
                <hr>
            </div>
    
            <div class="container">
                <ul class="nav nav-tabs" id="myTabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home"
                            type="button" role="tab" aria-controls="home" aria-selected="true">Description</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile"
                            type="button" role="tab" aria-controls="profile" aria-selected="false">Reviews</button>
                    </li>
    
                </ul>
    
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="details-para">
                            <h6>Product Details</h6>
                            <ul>
                                <li>Description</li>
                                
                                
                            </ul>
                        </div>
    
                    </div>
                    
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="container px-5">
                        <h2 class="customer-review">Customer Reviews</h2>
                    
                      <form class="form-horizontal" action="" method="post">
            
                        <input type="hidden" name="product_id" value="">
                        <div class="form-area">
                            <h2 class="write-review">Write Your Own Review</h2>
                          <div class="form-element">
                            <label>Nickname <em>*</em></label><br>
                            <input type="text" name="author" required="" autofocus="">
                          </div>
                          
                          <div class="form-element">
                            <label>Review <em>*</em></label><br>
                            <textarea required="" name="text"></textarea>
                          </div>
    
                          <div class="buttons-set">
                            <button class="button submit review-button" title="Submit Review" type="submit" ><span><i class="fa fa-thumbs-up"></i> &nbsp;Review</span></button>
                          </div>
    
                         </div>
                       </form>
    
                   
                        <div class="customer py-3">
                        <p>No reviews</p>
                        </div>
                       
                     
                
                      <a href="" class="btn btn-dark">Login To Customer Reviews</a>
                     
             
                       <div class="customer py-3" style="text-transform: capitalize;">
                           <h6>namw</h6>
      
                           <p>test<small>(Posted on date)</small></p>
                       </div>
                      
                     
    
    
            </div>
                            </div>
            
                        </div>
                    
                    </div>
                    </div>
           
                
          
            <div class="row">
                <div class="col-md-12">
                    <div class="related-product">
                         <h1>Related Products</h1>
                    </div>
                
                </div>
            </div>
            <div class="row py-5">

                {% for products in related_products %}


                <div class='newdesign'>
                    <a href="{{ products.get_url }}"> 
                      <img src="{{products.images.url}}" alt="">
          
                    <p style="font-size:14px;margin-bottom:0.5rem;">{{products.phone_name}}</p>
                    <p style="font-weight:600;font-size:18px;color: #f5831a;margin-bottom: 4px;" class="">{{products.phone_name}}</p>
                    <p style="font-weight:600;font-size:18px;color: #f5831a;margin-bottom: 4px;" class="">{{products.brand}}</p>
                    <div class="font-body"><span
                        style="font-weight:600;font-size:14px;color: #000;margin-bottom: 4px;text-decoration: line-through;"
                        class=" ">{{products.price}}</span> <span class=""
                        style="background-color: #f5831a;font-size: 12px;color: white;padding: 3px;">{{products.price}}</span></div>
          </a>
                      
                  </div>
    {% endfor %}
                   
            </div> 
            
        </section>
        <script>
            
            $(function(){
    
      $("#exzoom").exzoom({
    
        // thumbnail nav options
        "navWidth": 60,
        "navHeight": 60,
        "navItemNum": 5,
        "navItemMargin": 7,
        "navBorder": 1,
    
        // autoplay
        "autoPlay": false,
    
        // autoplay interval in milliseconds
        "autoPlayTimeout": 2000
        
      });
    
    });
            
        </script>
        
        
        
        
        
      <script>
        function showPopup() {
          // Display the popup box
          document.getElementById("popup-box").style.display = "block";
    
          // Automatically close the popup after 3 seconds
          setTimeout(function() {
            hidePopup();
          }, 2000);
        }
    
        function hidePopup() {
          // Hide the popup box
          document.getElementById("popup-box").style.display = "none";
        }
    </script> 
    
    
    
    
    
    <script>
    // Get the modal
    var modal = document.getElementById("myModal");
    
    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById("myImg");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function(){
      modal.style.display = "block";
      modalImg.src = this.src;
      captionText.innerHTML = this.alt;
    }
    
    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];
    
    // When the user clicks on <span> (x), close the modal
    span.onclick = function() { 
      modal.style.display = "none";
    }
    </script>
    
    
    
    
    

  
  {%endblock main-content%} 